export const LOADER = "LOADER";
export const FETCH_HEADER_SUCCESS = "FETCH_HEADER_SUCCESS";
export const FETCH_FOOTER_SUCCESS = "FETCH_FOOTER_SUCCESS";
export const FETCH_TOPBRANDS_SUCCESS = "FETCH_TOPBRANDS_SUCCESS";
export const ERROR = "ERROR";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_ITEM = "INCREMENT_ITEM";
export const DECREMENT_ITEM = "DECREMENT_ITEM";
export const RESET_CART = "RESET_CART";
export const TOGGLE_CART = "TOGGLE_CART";
export const ADD_TO_RECENTLY_VIEWED = "ADD_TO_RECENTLY_VIEWED";
export const CURRENT_LOCATION = "CURRENT_LOCATION";
export const CURRENCY = "CURRENCY";
export const CATEGORY = "CATEGORY";
export const SELECTED_CATEGORY = "SELECTED_CATEGORY";
export const TOGGLE_WISHLIST = "TOGGLE_WISHLIST";
export const TOGGLE_QUICKVIEW = "TOGGLE_QUICKVIEW";
export const STORE = "STORE";
export const SNACKBAR = "SNACKBAR";
export const GET_WISHLIST = "GET_WISHLIST";
export const ADD_WISHLIST = "ADD_WISHLIST";
export const CLEAR_WISHLIST = "CLEAR_WISHLIST";
export const REMOVE_WISHLIST = "REMOVE_WISHLIST";
export const LOADING_WISHLIST = "LOADING_WISHLIST";
export const SET_ATTRIBUTES = "SET_ATTRIBUTES";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_WITH_SOCIAL = "LOGIN_WITH_SOCIAL";
export const LOGOUT = "LOGOUT";
export const TOGGLE_SIGNUP_CARD = "TOGGLE_SIGNUP_CARD";
export const SET_CUSTOMER = "SET_CUSTOMER";
export const SET_CART_ID = "SET_CART_ID";
export const SET_BULK_CART = "SET_BULK_CART";
export const TOGGLE_ADDRESS = "TOGGLE_ADDRESS";
export const GET_ADDRESS = "GET_ADDRESS";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const REMOVE_ADDRESS = "REMOVE_ADDRESS";
export const PAYMENT_MODE = "PAYMENT_MODE";
export const SHIPPING_METHOD = "SHIPPING_METHOD";
export const CART_INFO = "CART_INFO";
export const CART_EXTRA_INFO = "CART_EXTRA_INFO";
export const SINGLE_CART = "SINGLE_CART";

export const GET_FREE_SHIPPING = "GET_FREE_SHIPPING";

export const NEW_USER_EMAIL = "NEW_USER_EMAIL";
export const FORGET_PASSOWORD_EMAIL = "FORGET_PASSOWORD_EMAIL";
export const ADD_RETURN_LIST = "ADD_RETURN_LIST";
export const CLEAR_RETURN_LIST = "CLEAR_RETURN_LIST";
export const CART_STATUS = "CART_STATUS";
export const CART_ADD_STATUS = "CART_ADD_STATUS";

// filters

export const FILTER_PARAMS = "FILTER_PARAMS";
export const CLEAR_FILTER_PARAMS = "CLEAR_FILTER_PARAMS";
export const CLEAR_SINGLE_VALUE = "CLEAR_SINGLE_VALUE";


// sorts
export const SET_SORT_FIELD = "SET_SORT_FIELD"